version: '3'

services:
  apache_img:
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    build:
      context: ./apache
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${WORK_ROOT_DIR}
        - LOG_APACHE_ROOT_DIR=${LOG_APACHE_ROOT_DIR}
        - PHP_74_IP=${PHP_74_IP}
        - PHP_74_EXPOSED_PORT=${PHP_74_EXPOSED_PORT}
    volumes:
      - ../src:${WORK_ROOT_DIR}
      - ../logs/apache:${LOG_APACHE_ROOT_DIR}
    ports:
      - ${APACHE_EXPOSED_PORT}:80
    networks:
      public_net:
        ipv4_address: ${APACHE_IP}
    environment:
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - APACHE_ROOT_DIR=${WORK_ROOT_DIR}
      - LOG_APACHE_ROOT_DIR=${LOG_APACHE_ROOT_DIR}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - PHP_74_IP=${PHP_74_IP}
      - PHP_74_EXPOSED_PORT=${PHP_74_EXPOSED_PORT}
      - WORK_ROOT_DIR=${WORK_ROOT_DIR}
  php_7_4_img:
    container_name: ${COMPOSE_PROJECT_NAME}_php_7_4
    build:
      context: ./php
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        - WORK_ROOT_DIR=${WORK_ROOT_DIR}
    volumes:
      - ../src:${WORK_ROOT_DIR}:delegated
      - ../logs/php:${PHP_ROOT_DIR}/logs
    ports:
      - ${PHP_74_EXPOSED_PORT}:9000
    networks:
      public_net:
        ipv4_address: ${PHP_74_IP}
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - WORK_ROOT_DIR=${WORK_ROOT_DIR}
      - APACHE_IP=${APACHE_IP}
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}