version: '3'

services:
  apache:
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    build:
      context: ./apache
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${WORK_ROOT_DIR}
        - LOG_APACHE_ROOT_DIR=${LOG_APACHE_ROOT_DIR}
        - PHP_74_IP=${PHP_74_IP}
        - PHP_74_EXPOSED_PORT=${PHP_74_EXPOSED_PORT}
    volumes:
      - ../src:${WORK_ROOT_DIR}
      - ../logs/apache:${LOG_APACHE_ROOT_DIR}
      - ./apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/conf/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    ports:
      - ${APACHE_EXPOSED_PORT}:80
    networks:
      public_net:
        ipv4_address: ${APACHE_IP}
    environment:
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - APACHE_ROOT_DIR=${WORK_ROOT_DIR}
      - LOG_APACHE_ROOT_DIR=${LOG_APACHE_ROOT_DIR}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - PHP_74_IP=${PHP_74_IP}
      - PHP_74_EXPOSED_PORT=${PHP_74_EXPOSED_PORT}
      - WORK_ROOT_DIR=${WORK_ROOT_DIR}
  php_7_4:
    container_name: ${COMPOSE_PROJECT_NAME}_php74
    build:
      context: ./php/74
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        - WORK_ROOT_DIR=${WORK_ROOT_DIR}
    volumes:
      - ../src:${WORK_ROOT_DIR}:delegated
      - ./php/74/www.conf:${PHP_ROOT_DIR}/php-fpm.d/www.conf
      - ../logs/php:${PHP_ROOT_DIR}/logs
      - ./php/composer/auth.json:/root/.composer/auth.json
    networks:
      public_net:
        ipv4_address: ${PHP_74_IP}
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - WORK_ROOT_DIR=${WORK_ROOT_DIR}
      - APACHE_IP=${APACHE_IP}
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - MYSQL_IP=${MYSQL_IP}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_EXPOSED_PORT=${MYSQL_EXPOSED_PORT}
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    build:
      context: ./mysql
      args:
        - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
        - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
    ports:
      - ${MYSQL_EXPOSED_PORT}:3306
    volumes:
      - ../logs/mysql:${MYSQL_LOG_DIR}
      - ../database:${MYSQL_DATA_DIR}
    networks:
      public_net:
        ipv4_address: ${MYSQL_IP}
    environment:
      - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
      - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PHP_MY_ADMIN_EXPOSED_PORT}:80
    environment:
      - PMA_HOST=${MYSQL_IP}
      - PMA_PORT=${MYSQL_EXPOSED_PORT}
      - PMA_USER=${MYSQL_ROOT_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      public_net:
        ipv4_address: ${PHP_MY_ADMIN_IP}
networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}