version: '3'

services:
  apache:
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    build:
      context: ./apache
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${WORK_ROOT_DIR}
        - LOG_APACHE_ROOT_DIR=${LOG_APACHE_ROOT_DIR}
        - PHP_74_IP=php_7_4
        - PHP_72_IP=php_7_2
        - PHP_56_IP=php_5_6
        - MYSQL_IP=mysql
    volumes:
      - ../../../projects:${WORK_ROOT_DIR}
      - ../logs/apache:${LOG_APACHE_ROOT_DIR}
      - ./apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/conf/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    ports:
      - ${APACHE_EXPOSED_PORT}:80
    restart: always
    environment:
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - APACHE_ROOT_DIR=${WORK_ROOT_DIR}
      - LOG_APACHE_ROOT_DIR=${LOG_APACHE_ROOT_DIR}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - PHP_74_IP=php_7_4
      - PHP_72_IP=php_7_2
      - PHP_56_IP=php_5_6
      - WORK_ROOT_DIR=${WORK_ROOT_DIR}
      - MYSQL_IP=mysql
  php_7_4:
    container_name: ${COMPOSE_PROJECT_NAME}_php74
    build:
      context: ./php/74
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        - WORK_ROOT_DIR=${WORK_ROOT_DIR}
        - MYSQL_IP=mysql
    volumes:
      - ../../../projects:${WORK_ROOT_DIR}:delegated
      - ./php/74/www.conf:${PHP_ROOT_DIR}/php-fpm.d/www.conf
      - ./php/74/php.ini:${PHP_ROOT_DIR}/php/conf.d/php.ini
      - ../logs/php:${PHP_ROOT_DIR}/logs
      - ./php/composer/auth.json:/root/.composer/auth.json
    restart: always
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - WORK_ROOT_DIR=${WORK_ROOT_DIR}
      - APACHE_IP=apache
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - MYSQL_IP=mysql
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_EXPOSED_PORT=${MYSQL_EXPOSED_PORT}
      - ELASTIC_IP=elasticsearch
      - REDIS_IP=redis
  php_7_2:
    container_name: ${COMPOSE_PROJECT_NAME}_php72
    build:
      context: ./php/72
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        - WORK_ROOT_DIR=${WORK_ROOT_DIR}
    volumes:
      - ../../../projects:${WORK_ROOT_DIR}:delegated
      - ./php/72/www.conf:${PHP_ROOT_DIR}/php-fpm.d/www.conf
      - ./php/72/php.ini:${PHP_ROOT_DIR}/php/conf.d/php.ini
      - ../logs/php:${PHP_ROOT_DIR}/logs
      - ./php/composer/auth.json:/root/.composer/auth.json
    restart: always
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - WORK_ROOT_DIR=${WORK_ROOT_DIR}
      - APACHE_IP=apache
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - MYSQL_IP=mysql
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_EXPOSED_PORT=${MYSQL_EXPOSED_PORT}
      - ELASTIC_IP=elasticsearch
      - REDIS_IP=redis
  php_5_6:
    container_name: ${COMPOSE_PROJECT_NAME}_php56
    build:
      context: ./php/56
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        - WORK_ROOT_DIR=${WORK_ROOT_DIR}
    volumes:
      - ../../../projects:${WORK_ROOT_DIR}:delegated
      - ./php/56/www.conf:${PHP_ROOT_DIR}/php-fpm.d/www.conf
      - ./php/56/php.ini:${PHP_ROOT_DIR}/php/conf.d/php.ini
      - ../logs/php:${PHP_ROOT_DIR}/logs
      - ./php/composer/auth.json:/root/.composer/auth.json
    restart: always
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - WORK_ROOT_DIR=${WORK_ROOT_DIR}
      - APACHE_IP=apache
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - MYSQL_IP=mysql
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_EXPOSED_PORT=${MYSQL_EXPOSED_PORT}
      - ELASTIC_IP=elasticsearch
      - REDIS_IP=redis
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    build:
      context: ./mysql
      args:
        - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
        - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
    restart: always
    ports:
      - ${MYSQL_EXPOSED_PORT}:3306
    volumes:
      - ../logs/mysql:${MYSQL_LOG_DIR}
      - ../database:${MYSQL_DATA_DIR}
    environment:
      - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
      - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PHP_MY_ADMIN_EXPOSED_PORT}:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_ROOT_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
    restart: always
    ports:
      - ${ELASTIC_SEARCH_EXPOSED_PORT}:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  redis:
    image: redis
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: always
    ports:
      - ${REDIS_EXPOSED_PORT}:6379